name: Update GitHub Stats Gist
on:
    workflow_dispatch:
    schedule:
        - cron: '0 */12 * * *'
    push:
        branches: master
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@master
              with:
                  node-version: 16
            - run: npx github-stats-box@1
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  GIST_ID: 0cda5851ab8a063fef18c993a434dc68
                  ALL_COMMITS: true
                  K_FORMAT: false
